import numpy as np

import process_data as data_proc
import transform
import optimize as optim
import fit_model as fit
import resample


def build_obsLE(beta_ds,
                residuals_da,
                block_size,
                surrogate_modes,
                mode_list,
                lam,
                offset,
                save_path):
    """
    Build Observational Large Ensemble (Obs-LE) members from the fitted regression 
    coefficients and the residuals.

    Parameters
    ----------
    beta_ds: xr.Dataset, dims: (month, lat, lon)
        Dataset containing the fitted beta coefficients from the linear models
        for each climate mode fitted for each month and location. These coefficients
        are held fixed in the Obs-LE. See fit_model.fit_linear_model() and 
        fit_model.build_model_ds() for additional details.
        
    residuals_da: xr.DataArray, dims: (time, lat, lon)
        DataArray containing the residuals from the fitted linear models.

    block_size: int
        Integer giving the block size in months for the moving block bootstrap. 
        Must be divisible by 12 to ensure that whole years are included, 
        preserving seasonality.
        
    surrogate_modes: np.ndarray, dims: (n_ensemble_members, n_climate_modes, n_time)
        Numpy array containing the surrogate climate modes generated by IAAFT. See
        resample.iaaft() for more details. The first dimension contains different
        sets of surrogate climate modes, the second dimension indexes the climate 
        mode, and the last dimension indexes the time series time index.
        
    mode_list: list of str
        list containing the names of the climate modes. Names should match the
        variable names in beta_ds, and the order should match the order in
        surrogate_modes.

    lam: xr.DataArray, dims: (month, lat, lon)
        DataArray containing the power paramter, lambda, of the Box-Cox transform.
        Used for transforming the newly generated values back into the original
        precipitation space. See transform.inv_boxcox_transform() for details.

    offset: xr.DataArray, dims: (month, lat, lon)
        DataArray containing the offset parameter of the Box-Cox transform. Used
        for transforming teh newly generated values back into the original 
        precipitation space. See transform.inv_boxcox_transform() for details.

    save_path: str
        Path to the directory for saving the outputted ensemble members. Directory
        name should end in /. Members are saved in netCDF file format at:
        save_path + 'obsLE_member{member #}.nc'.

    Returns
    -------
    None
    """

    n_ens = surrogate_modes.shape[0]
    
    mode_index = np.searchsorted(beta_ds.month, residuals_da['time.month'])

    for k in range(n_ens):
        bootstrap_residuals = resample.bootstrap_residuals(residuals_da,
                                                           block_size=block_size)
    
        surrogate_mat = np.transpose(surrogate_modes[k])
    
        p = surrogate_mat.shape[1]
        n = surrogate_mat.shape[0]
    
        mean_field = beta_ds['intercept'][mode_index]
    
        for j in range(p):
            surrogate_ts = surrogate_mat[:, j].reshape((n, 1, 1))
            beta_mode = beta_ds[mode_list[j]]
    
            mean_field = mean_field + beta_mode[mode_index].values * surrogate_ts
    
        mean_field = mean_field.rename({'month': 'time'})
        mean_field = mean_field.assign_coords({'time': residuals_da.time})
    
        obsLE_member = mean_field + bootstrap_residuals
    
        obsLE_member = transform.inv_boxcox_transform(obsLE_member,
                                                      offset=offset,
                                                      lam=lam)
        
        member_savename = save_path + f'obsLE_member{k + 1:04}.nc'

        obsLE_member.to_netcdf(member_savename)

def obsLE_pipeline(n_ens_members,
                   target_da,
                   mode_path,
                   start_year,
                   end_year,
                   mode_list,
                   lambda_values,
                   offset_values,
                   fit_seasonal,
                   block_size,
                   save_path):
    """Construct the Observational Large Ensemble (Obs-LE).
    
    Parameters
    ----------
    n_ens_members, int
        number of ensemble members to build.

    target_da, xr.DataArray, dims: (time, lat, lon)
        DataArray containing the target variable for building the Obs-LE.

    mode_path: str
        Path to the directory containing the climate mode files.

    start_year: str
        First year to include in the Obs-LE. String with four digit year.

    end_year: str
        Last year to include in the Obs-LE. String with four digit year.

    mode_list: list of str
        list containing the names of the climate modes to include.

    lambda_values: list of numeric
         List containing Box-Cox power paramters to optimize over for the
         transformation applied to target_da. Values for the transform are 
         restricted to be positive.

    offset_values: list of numeric
        List containing offsets to be optimized over for shifting target_da before
        apply Box-Cox transform. If there are zeros in the data, offset_values 
        should be positive values such that target_da + offset_values is positive 
        everywhere. Selecting a single value such as [1e-6] works well in practice.

    fit_seasonal: list of bools
        True/False values with length = len(mode_list). True specifies that the
        seasonal cycle in the variance should be maintained in the surrogate modes.
        For most climate modes, fit_seasonal should be True, since there can be
        large differences in variance between months. The trade-off is an increased
        number of iterations before IAAFT converges.

    block_size: int
        The length of time blocks, in months, to use for the moving block bootstrap.
        Must be divisible by 12, so that only whole years are included.

    save_path: str
        Path to the directory in which to save the outputted Obs-LE members. Should
        end in /. Individual members are saved as netCDF files at:
        save_path + 'obsLE_member{member #}.nc'
    """
    
    ortho_mode_df = data_proc.build_ortho_mode_df(mode_path=mode_path,
                                                  start_year=start_year,
                                                  end_year=end_year,
                                                  mode_list=mode_list,
                                                  save_path=save_path)
    
    param_ds, llik_ds = optim.optimize_transform(target_da=target_da,
                                                 ortho_mode_df=ortho_mode_df,
                                                 lambda_values=lambda_values,
                                                 offset_values=offset_values,
                                                 save_path=save_path)
    
    beta, lm_out = fit.fit_optimized_model(target_da=target_da,
                                           ortho_mode_df=ortho_mode_df,
                                           lam=param_ds['lam'],
                                           offset=param_ds['offset'])

    residuals_da = lm_out['residuals']

    surrogate_modes = resample.create_surrogate_modes(ortho_mode_df,
                                                      fit_seasonal=fit_seasonal,
                                                      n_ens_members=n_ens_members)[0]

    
    build_obsLE(beta_ds=beta, 
                residuals_da=residuals_da,
                block_size=block_size,
                surrogate_modes=surrogate_modes,
                mode_list=mode_list,
                lam=param_ds['lam'],
                offset=param_ds['offset'],
                save_path=save_path)
